apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      labels:
        app: client
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "client"
        dapr.io/protocol: "grpc"
        dapr.io/port: "4000"
    spec:
      containers:
      - image: dapr0acr0prexqb.azurecr.io/actor-go-client:5
        name: client
        resources: {}
        ports:
        - containerPort: 4000
        env:
        - name: DAPR_GRPC_PORT
          value: "50001"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: client
  name: client
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: client
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: caller
  name: caller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caller
  strategy: {}
  template:
    metadata:
      labels:
        app: caller
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "caller"
        dapr.io/protocol: "grpc"
    spec:
      containers:
      - image: dapr0acr0prexqb.azurecr.io/actor-go-caller:7
        name: caller
        resources: {}
        env:
        - name: DAPR_GRPC_PORT
          value: "50001"
