apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      labels:
        app: client
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "client"
        dapr.io/protocol: "grpc"
        dapr.io/port: "4000"
    spec:
      containers:
      - image: dapr0acr0prexqb.azurecr.io/actor-go-client:4
        name: client
        resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: caller
  name: caller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caller
  strategy: {}
  template:
    metadata:
      labels:
        app: caller
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "caller"
        dapr.io/protocol: "grpc"
    spec:
      containers:
      - image: dapr0acr0prexqb.azurecr.io/actor-go-caller:6
        name: caller
        resources: {}
        env:
        - name: DAPR_GRPC_PORT
          value: "50001"
